### ISSUE TITLE
Potential loss of all identities due to remaining centralization

### ISSUE THREAD

**Issue by taoeffect** [blockstack/registrar#24]
At the moment, all Blockchain IDs registered through Onename are vulnerable to loss.

Hackers able to hack into Onename's servers could obtain the private keys to everyone's identity, and if they were able to do that they would own them. Unlike identities stored on Twitter or Google, there would be little Onename could do to return them back to their rightful owners.

**Comment by muneeb-ali** [comment]
We are working on releasing client-side software which will be the default software users will use instead of the current web app.

Also users can transfer out their blockchain ID to any Bitcoin address that they own, even currently.

Client side software is the only real solution to what you are mentioning and that's exactly what we are doing.
